server:
    ssl:
        key-store: classpath:keystore.p12
        key-store-password: springboot
        key-store-type: pkcs12
        key-alias: springboot
        key-password: springboot
    port: 8443
